name: action

on: [pull_request]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.server_url }}
          echo ${{ github.repository }}
          echo ${{ github.run_id }}
