name: docs-preview

on: [pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      RTD_AUTH_TOKEN: ${{ secrets.RTD_AUTH_TOKEN }}
      RTD_PROJ_URL: https://readthedocs.org/api/v3/projects
      PROJ_SLUG: sphinx-template-docs
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.5
      - name: Update working project
        env:
          REPOSITORY_URL: https://github.com/${{ github.repository }}.git
        run: |
          RESP_CODE=$(curl \
            -X PATCH \
            -H "Authorization: Token $RTD_AUTH_TOKEN" $RTD_PROJ_URL/$PROJ_SLUG/ \
            -H "Content-Type: application/json" \
            -d '{"repository": {"url": $REPOSITORY_URL, "type": "git"}}' \
            -o /dev/null -w '%{http_code}\n' -s
          )
          if [ $RESP_CODE -eq 204 ]
          then
            echo "Successfully update $PROJ_SLUG"
          else
            exit 1
          fi

      - name: Activate Branch
        env:
          VER_SLUG: ${{ steps.branch-name.outputs.current_branch }}
        run: |
          RESP_CODE=$(curl \
            -X PATCH \
            -H "Authorization: Token $RTD_AUTH_TOKEN" $RTD_PROJ_URL/$PROJ_SLUG/versions/$VER_SLUG/ \
            -H "Content-Type: application/json" \
            -d '{"active": true, "hidden": false}' -o /dev/null -w '%{http_code}\n' -s
          )
          echo $RESP_CODE
          if [ $RESP_CODE -eq 204 ]
          then
            echo "Automatically activate $VER_SLUG version of $PROJ_SLUG"
          else
            echo "Invalid"
            exit 1
          fi

      - name: Trigger a New Build
        env:
          VER_SLUG: ${{ steps.branch-name.outputs.current_branch }}
        run: |
          RESP_CODE=$(curl \
            -X PATCH \
            -H "Authorization: Token RTD_AUTH_TOKEN" $RTD_PROJ_URL/$PROJ_SLUG/versions/$VER_SLUG/builds/ \
            -o /dev/null -w '%{http_code}\n' -s
          )
          if [ $RESP_CODE -eq 202 ]
          then
            echo "Build triggering success: $VER_SLUG version of $PROJ_SLUG"
          else
            exit 1
          fi

      - name: Deactivate Branch
        env:
          VER_SLUG: ${{ steps.branch-name.outputs.current_branch }}
        run: |
          RESP_CODE=$(curl \
            -X PATCH \
            -H "Authorization: Token RTD_AUTH_TOKEN" $RTD_PROJ_URL/$PROJ_SLUG/versions/$VER_SLUG/ \
            -H "Content-Type: application/json" \
            -d '{"active": false, "hidden": false}' -o /dev/null -w '%{http_code}\n' -s
          )
          if [ $RESP_CODE -eq 204 ]
          then
            echo "Automatically deactivate $VER_SLUG version of $PROJ_SLUG"
          else
            exit 1
          fi