name: label

on: 
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sparse-checkout
      uses: lablup/sparse-checkout@v1
      with:
        patterns: |
          changes
          scripts
          packages
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        check-latest: true
    - name: Check PR labels
      env:
        PR_LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
        PR_NAME: ${{ github.event.pull_request.title }}
      run: |
        echo $PR_LABELS $PR_NAME
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools
        python -m pip install -U towncrier~=21.9
    - name: Check existence of news fragment
      run: |
        git fetch --no-tags origin +refs/heads/${BASE_BRANCH}:refs/remotes/origin/${BASE_BRANCH} &&
        python -m towncrier.check
      env:
        BASE_BRANCH: ${{ github.base_ref }}