name: label

on: 
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Check PR labels
      env:
        PR_LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
      run: echo $PR_LABELS
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        check-latest: true
    - name: Install Dependencies
      run: |
        python -m pip install -U pip setuptools
        python -m pip install -U towncrier~=21.9
    - name: Check existence of news fragment
      env:
        BASE_BRANCH: ${{ github.base_ref }}
      run: |
        git fetch --no-tags origin +refs/heads/${BASE_BRANCH}:refs/remotes/origin/${BASE_BRANCH}
        python -m towncrier.check --compare-with=origin/${BASE_BRANCH}