name: label

on: 
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  build:
    steps:
      - name: Check PR labels
        env:
          PR_LABELS: ${{ github.event.pull_request.labels.*.name }}
        run:
          echo $PR_LABELS
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install -U pip setuptools
          python -m pip install -U towncrier~=21.9
      - name: Check existence of news fragment
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        run: |
          echo $BASE_BRANCH
          git fetch --no-tags origin +refs/heads/${BASE_BRANCH}:refs/remotes/origin/${BASE_BRANCH}
          python -m towncrier.check --compare-with=origin/${BASE_BRANCH}