name: numbering

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - name: Check Issue & PR Number
        run: |
          echo ${{ fromJSON(github.event.pull_request.labels) }}
          echo ${{ fromJSON(github.event.pull_request.labels.*) }}
          echo ${{ fromJSON(github.event.pull_request.labels.*.name) }}
          echo ${{ github.evnet.number }}
          echo ${{ github.event.pull_request.number }}
          echo ${{ github.event.issue.number }}